/* Lux Tech — Admin V2: responsive dashboard + inventory/sales/order automation */
const CLOUDINARY_CLOUD_NAME="jaj006bc";
const CLOUDINARY_UPLOAD_PRESET="lux-tech";
const CLOUDINARY_UPLOAD_URL=`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`;
let categoriesCache=[],productsCache=[],latestOrders=[],paymentRequestsCache=[],branchesCache=[],couponsCache=[],messagesCache=[],unsubscribeFns=[],currentUser=null;
let storeSettings={cashOnDeliveryEnabled:true,instapayEnabled:false,walletEnabled:false,instapay:{},wallet:{}};
let socialLinks={};
const COLLECTIONS_FALLBACK={products:"products",categories:"categories",orders:"orders",admins:"admins"};
const ORDER_STATUSES=["جديد","قيد التجهيز","تم الشحن","تم التسليم","ملغي"];
const pageNames={dashboard:["نظرة عامة","لوحة التحكم"],products:["إدارة المتجر","المنتجات"],inventory:["إدارة المتجر","المخزون والجرد"],orders:["إدارة المتجر","الطلبات"],categories:["إدارة المتجر","الأقسام"],sales:["التحليلات","المبيعات"],reports:["التحليلات","التقارير"],payments:["إدارة المتجر","الدفع"],branches:["إدارة المتجر","الفروع"],links:["إدارة المتجر","الروابط"],messages:["إدارة المتجر","الرسائل"],coupons:["إدارة المتجر","كوبونات الخصم"]};
const C=()=>typeof COLLECTIONS!=="undefined"?COLLECTIONS:COLLECTIONS_FALLBACK;
const money=n=>new Intl.NumberFormat("ar-EG").format(Number(n)||0)+" ج.م";
const num=n=>new Intl.NumberFormat("ar-EG").format(Number(n)||0);
const getProduct=id=>productsCache.find(p=>p.id===id);
const orderTotal=o=>Number(o.total)||((o.items||[]).reduce((s,i)=>s+(Number(i.price)||getProduct(i.productId)?.price||0)*(Number(i.qty)||0),0));
const isCompleted=o=>o.status==="تم التسليم";
function toast(msg){const e=document.getElementById("toast");e.textContent=msg;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2300)}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}

/* Login */
async function doLogin(){const email=document.getElementById("loginEmail").value.trim(),pass=document.getElementById("loginPass").value,btn=document.getElementById("loginBtn"),err=document.getElementById("loginError");err.style.display="none";if(!email||!pass){err.textContent="اكتب البريد الإلكتروني وكلمة المرور";err.style.display="block";return}btn.disabled=true;btn.textContent="جاري الدخول...";sessionStorage.setItem("luxtech_admin_session","1");try{await auth.setPersistence(firebase.auth.Auth.Persistence.SESSION);await auth.signInWithEmailAndPassword(email,pass)}catch(e){sessionStorage.removeItem("luxtech_admin_session");err.textContent="بيانات الدخول غير صحيحة";err.style.display="block"}finally{btn.disabled=false;btn.textContent="تسجيل الدخول"}}
async function doLogout(){try{sessionStorage.removeItem("luxtech_admin_session");await auth.signOut();document.getElementById("app").style.display="none";document.getElementById("loginScreen").style.display="grid";document.getElementById("loginPass").value="";}catch(e){console.error(e);toast("تعذر تسجيل الخروج")}}
// SESSION keeps the admin logged in across refreshes, but the marker disappears when the tab/site session ends.
// If Firebase has an old LOCAL session from a previous version, force a fresh login.
auth.setPersistence(firebase.auth.Auth.Persistence.SESSION).catch(()=>{});
auth.onAuthStateChanged(async user=>{currentUser=user;if(!user){document.getElementById("loginScreen").style.display="grid";document.getElementById("app").style.display="none";cleanupListeners();return}if(sessionStorage.getItem("luxtech_admin_session")!=="1"){await auth.signOut();return}try{const a=await db.collection(C().admins).doc(user.uid).get();if(!a.exists){const err=document.getElementById("loginError");err.textContent="هذا الحساب ليس لديه صلاحية الأدمن";err.style.display="block";await auth.signOut();return}document.getElementById("loginScreen").style.display="none";document.getElementById("app").style.display="block";initAdminData()}catch(e){console.error(e);toast("تعذر التحقق من صلاحية الأدمن");await auth.signOut()}});

/* Responsive navigation */
function openSidebar(){document.getElementById("sidebar").classList.add("open");document.getElementById("sidebarOverlay").classList.add("open")}
function closeSidebar(){document.getElementById("sidebar").classList.remove("open");document.getElementById("sidebarOverlay").classList.remove("open")}
function showPage(name){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.page===name));document.getElementById("page-"+name).classList.add("active");document.getElementById("breadcrumb").textContent=pageNames[name][0];document.getElementById("pageTitle").textContent=pageNames[name][1];closeSidebar();renderAll()}

function cleanupListeners(){unsubscribeFns.forEach(fn=>{try{fn()}catch{}});unsubscribeFns=[]}
function initAdminData(){cleanupListeners();
 unsubscribeFns.push(db.collection(C().categories).orderBy("order","asc").onSnapshot(s=>{categoriesCache=s.docs.map(d=>({id:d.id,...d.data()}));renderCategoriesTable();populateCategorySelect();renderAll()} ,e=>console.error(e)));
 unsubscribeFns.push(db.collection(C().products).onSnapshot(s=>{productsCache=s.docs.map(d=>({id:d.id,...d.data()}));renderProductsTable();renderAll()},e=>console.error(e)));
 unsubscribeFns.push(db.collection(C().orders).orderBy("createdAt","desc").onSnapshot(s=>{latestOrders=s.docs.map(d=>({id:d.id,...d.data()}));renderOrdersTable();renderAll()},e=>console.error(e)));
 unsubscribeFns.push(db.collection("paymentRequests").orderBy("createdAt","desc").onSnapshot(s=>{paymentRequestsCache=s.docs.map(d=>({id:d.id,...d.data()}));renderPaymentRequests()},e=>console.error(e)));
 unsubscribeFns.push(db.collection("branches").orderBy("order","asc").onSnapshot(s=>{branchesCache=s.docs.map(d=>({id:d.id,...d.data()}));renderBranches()},e=>console.error(e)));
 unsubscribeFns.push(db.collection("storeSettings").doc("main").onSnapshot(s=>{storeSettings={...storeSettings,...(s.exists?s.data():{})};fillSettingsForms();renderPaymentRequests();},e=>console.error(e)));
 unsubscribeFns.push(db.collection("socialLinks").doc("main").onSnapshot(s=>{socialLinks=s.exists?s.data():{};fillSocialLinks();},e=>console.error(e)));
 unsubscribeFns.push(db.collection("coupons").onSnapshot(s=>{couponsCache=s.docs.map(d=>({id:d.id,...d.data()}));renderCoupons();},e=>console.error("Coupons error",e)));
 unsubscribeFns.push(db.collection("messages").orderBy("createdAt","desc").onSnapshot(s=>{messagesCache=s.docs.map(d=>({id:d.id,...d.data()}));renderMessages();},e=>console.error("Messages error",e)));
}
function renderAll(){renderDashboard();renderProductsTable();renderInventory();renderOrdersTable();renderCategoriesTable();renderSales();renderReports();renderCoupons();renderMessages();populateCategorySelect();renderFilters();fillMessagingSettings()}

/* Dashboard */
function completedRevenue(){return latestOrders.filter(isCompleted).reduce((s,o)=>s+orderTotal(o),0)}
function stockValue(){return productsCache.reduce((s,p)=>s+(Number(p.stock)||0)*(Number(p.price)||0),0)}
function lowProducts(){return productsCache.filter(p=>(Number(p.stock)||0)<=Number(p.lowStock??p.low??5))}
function updateTopStats(){document.getElementById("statSales").textContent=money(completedRevenue());document.getElementById("statStockValue").textContent=money(stockValue());document.getElementById("statOrders").textContent=num(latestOrders.length);document.getElementById("statPending").textContent=num(latestOrders.filter(o=>["جديد","قيد التجهيز","تم الشحن"].includes(o.status)).length)+" طلب قيد التنفيذ";document.getElementById("statProducts").textContent=num(productsCache.length);document.getElementById("statLow").textContent=num(lowProducts().length)+" مخزون منخفض";document.getElementById("alertCount")&&(document.getElementById("alertCount").textContent=lowProducts().length)}
function renderDashboard(){updateTopStats();document.getElementById("today").textContent=new Intl.DateTimeFormat("ar-EG",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());const low=document.getElementById("lowStockList");low.innerHTML=lowProducts().slice(0,6).map(p=>`<div class="compact-item"><div><strong>${escapeHtml(p.name)}</strong><small>المتاح ${num(p.stock)} · حد التنبيه ${num(p.lowStock??p.low??5)}</small></div><i class="dot ${Number(p.stock)===0?"danger":""}"></i></div>`).join("")||`<div class="empty-note">لا توجد تنبيهات حاليًا.</div>`;document.getElementById("latestOrders").innerHTML=latestOrders.slice(0,6).map(o=>`<tr><td><strong>${escapeHtml(o.id)}</strong></td><td>${escapeHtml(o.customer?.name||"—")}</td><td class="money">${money(orderTotal(o))}</td><td>${statusBadge(o.status)}</td><td>${formatDate(o.createdAt)}</td></tr>`).join("")||`<tr><td colspan="5" class="empty-note">لا توجد طلبات.</td></tr>`;const top=productsCache.slice().sort((a,b)=>(b.stock*b.price)-(a.stock*a.price)).slice(0,6);document.getElementById("topStockList").innerHTML=top.map((p,i)=>`<div class="stock-rank"><span class="rank-num">${i+1}</span><div><strong>${escapeHtml(p.name)}</strong><small>${num(p.stock)} قطعة × ${money(p.price)}</small></div><b>${money(p.stock*p.price)}</b></div>`).join("")||`<div class="empty-note">لا توجد منتجات.</div>`;renderChart()}
function formatDate(v){if(!v)return"—";try{const d=v.toDate?v.toDate():new Date(v);return new Intl.DateTimeFormat("ar-EG",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d)}catch{return"—"}}
function statusBadge(s){const c=s==="تم التسليم"?"ok":s==="ملغي"?"danger":"warn";return`<span class="status ${c}">${escapeHtml(s||"—")}</span>`}
function renderChart(){const days=Number(document.getElementById("salesPeriod")?.value||7),count=Math.min(days,14),arr=[];for(let i=count-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);const value=latestOrders.filter(o=>isCompleted(o)&&dateKey(o.createdAt)===key).reduce((s,o)=>s+orderTotal(o),0);arr.push({label:d.toLocaleDateString("ar-EG",{day:"numeric",month:"numeric"}),value})}const max=Math.max(...arr.map(x=>x.value),1);document.getElementById("salesChart").innerHTML=arr.map(x=>`<div class="bar" title="${money(x.value)}" style="height:${Math.max(7,x.value/max*88)}%"><small>${x.label}</small></div>`).join("")}
function dateKey(v){try{const d=v?.toDate?v.toDate():new Date(v);return d.toISOString().slice(0,10)}catch{return""}}
document.getElementById("salesPeriod").addEventListener("change",renderChart);

/* Product / category filters */
function renderFilters(){const q=(document.getElementById("productSearch")?.value||"").toLowerCase().trim(),cat=document.getElementById("productCategoryFilter")?.value||"";return{q,cat}}
function populateCategorySelect(){const sel=document.getElementById("pf_category");if(!sel)return;const old=sel.value;sel.innerHTML=categoriesCache.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.name)}</option>`).join("");if(old)sel.value=old;const f=document.getElementById("productCategoryFilter"),fOld=f.value;f.innerHTML=`<option value="">كل الأقسام</option>`+categoriesCache.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.name)}</option>`).join("");if(fOld)f.value=fOld}
function renderProductsTable(){const body=document.getElementById("productsTableBody");if(!body)return;const {q,cat}=renderFilters();const list=productsCache.filter(p=>(!q||String(p.name||"").toLowerCase().includes(q))&&(!cat||p.category===cat));body.innerHTML=list.map(p=>`<tr><td><div class="product-cell"><img class="row-img" src="${escapeHtml(p.image||"https://placehold.co/80x80/161418/c9a24b?text=LT")}" onerror="this.src='https://placehold.co/80x80/161418/c9a24b?text=LT'"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.id)}</small></div></div></td><td>${escapeHtml(categoriesCache.find(c=>c.id===p.category)?.name||"—")}</td><td class="money">${money(p.price)}</td><td>${num(p.stock)}</td><td class="money">${money(p.stock*p.price)}</td><td>${num(soldForProduct(p.id))}</td><td class="money">${money(salesForProduct(p.id))}</td><td><div class="row-actions"><button class="mini" onclick="openProductForm('${p.id}')">✎</button><button class="mini" onclick="adjustStock('${p.id}')">±</button><button class="mini" onclick="deleteProduct('${p.id}')">×</button></div></td></tr>`).join("")||`<tr><td colspan="8" class="empty-note">لا توجد منتجات مطابقة.</td></tr>`}
function soldForProduct(id){return latestOrders.filter(isCompleted).reduce((s,o)=>s+(o.items||[]).filter(i=>i.productId===id).reduce((a,i)=>a+Number(i.qty||0),0),0)}
function salesForProduct(id){return latestOrders.filter(isCompleted).reduce((s,o)=>s+(o.items||[]).filter(i=>i.productId===id).reduce((a,i)=>a+(Number(i.qty)||0)*(Number(i.price)||getProduct(id)?.price||0),0),0)}
document.getElementById("productSearch").addEventListener("input",renderProductsTable);document.getElementById("productCategoryFilter").addEventListener("change",renderProductsTable);document.getElementById("globalSearch").addEventListener("input",e=>{const q=e.target.value.trim();if(q){showPage("products");document.getElementById("productSearch").value=q;renderProductsTable()}});

/* Inventory */
function renderInventory(){const totalQty=productsCache.reduce((s,p)=>s+Number(p.stock||0),0),low=lowProducts().length,out=productsCache.filter(p=>Number(p.stock||0)===0).length;document.getElementById("inventoryTotal").textContent=money(stockValue());document.getElementById("inventoryCards").innerHTML=`<div class="inventory-card"><small>إجمالي القطع المتاحة</small><strong>${num(totalQty)}</strong></div><div class="inventory-card gold"><small>قيمة المخزون الحالية</small><strong>${money(stockValue())}</strong></div><div class="inventory-card"><small>مخزون منخفض</small><strong>${num(low)}</strong></div><div class="inventory-card"><small>منتجات نافدة</small><strong>${num(out)}</strong></div>`;document.getElementById("inventoryTableBody").innerHTML=productsCache.map(p=>{const s=Number(p.stock||0),limit=Number(p.lowStock??p.low??5);return`<tr><td><strong>${escapeHtml(p.name)}</strong></td><td class="money">${money(p.price)}</td><td>${num(s)}</td><td class="money">${num(s)} × ${money(p.price)}</td><td class="money">${money(s*p.price)}</td><td>${s===0?'<span class="status danger">نفد</span>':s<=limit?'<span class="status warn">منخفض</span>':'<span class="status ok">متوفر</span>'}</td><td><button class="mini" onclick="adjustStock('${p.id}')">±</button></td></tr>`}).join("")||`<tr><td colspan="7" class="empty-note">لا توجد منتجات.</td></tr>`}
function adjustStock(id){const p=getProduct(id);if(!p)return;openModal(`<div class="modal-head"><span>INVENTORY</span><h2>جرد — ${escapeHtml(p.name)}</h2><p>يمكنك إضافة كمية أو خصم كمية يدويًا.</p></div><div class="form-group"><label>المخزون الحالي</label><input id="stockCurrent" value="${p.stock||0}" disabled></div><div class="form-group"><label>تعديل الكمية (+ إضافة / - خصم)</label><input id="stockDelta" type="number" placeholder="مثال: 10 أو -2"></div><div class="modal-foot"><button class="btn-primary" onclick="saveStock('${id}')">حفظ الجرد</button><button class="btn-secondary" onclick="closeOrderModal()">إلغاء</button></div>`) }
async function saveStock(id){const d=Number(document.getElementById("stockDelta").value);if(!Number.isFinite(d)||d===0)return toast("أدخل كمية صحيحة");const ref=db.collection(C().products).doc(id);try{await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("المنتج غير موجود");const current=Number(snap.data().stock||0),next=current+d;if(next<0)throw new Error("الكمية لا يمكن أن تكون أقل من صفر");tx.update(ref,{stock:next,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});const mref=db.collection(C().inventoryMovements||"inventory_movements").doc();tx.set(mref,{productId:id,productName:snap.data().name||"",type:d>0?"manual_add":"manual_remove",quantity:Math.abs(d),delta:d,before:current,after:next,createdAt:firebase.firestore.FieldValue.serverTimestamp(),adminUid:currentUser?.uid||null})});closeOrderModal();toast("تم تحديث المخزون وتسجيل حركة الجرد")}catch(e){toast(e.message||"تعذر تحديث المخزون")}}

/* Products */
function openProductForm(id){if(!categoriesCache.length){toast("أضف قسمًا واحدًا على الأقل أولًا");return}const p=id?getProduct(id):null;document.getElementById("productFormTitle").textContent=id?"تعديل منتج":"إضافة منتج";document.getElementById("pf_id").value=id||"";document.getElementById("pf_name").value=p?.name||"";document.getElementById("pf_price").value=p?.price??"";document.getElementById("pf_oldPrice").value=p?.oldPrice??"";document.getElementById("pf_category").value=p?.category||categoriesCache[0].id;document.getElementById("pf_stock").value=p?.stock??0;document.getElementById("pf_lowStock").value=p?.lowStock??p?.low??5;document.getElementById("pf_available").value=String(p?.available!==false);document.getElementById("pf_description").value=p?.description||"";document.getElementById("pf_specs").value=Array.isArray(p?.specs)?p.specs.join(", "):(p?.specs||"");resetImageBox("pf_image","pf_imagePreview","pf_uploadHint","pf_imageUrlManual",p?.image||"");document.getElementById("productFormOverlay").classList.add("open")}
function closeProductForm(){document.getElementById("productFormOverlay").classList.remove("open")}
async function saveProduct(){const id=document.getElementById("pf_id").value;const data={name:document.getElementById("pf_name").value.trim(),price:Number(document.getElementById("pf_price").value),oldPrice:Number(document.getElementById("pf_oldPrice").value)||null,category:document.getElementById("pf_category").value,image:document.getElementById("pf_image").value.trim(),stock:Number(document.getElementById("pf_stock").value)||0,lowStock:Number(document.getElementById("pf_lowStock").value)||5,available:document.getElementById("pf_available").value==="true",description:document.getElementById("pf_description").value.trim(),specs:document.getElementById("pf_specs").value.split(",").map(x=>x.trim()).filter(Boolean)};if(!data.name||!Number.isFinite(data.price)||data.price<0||data.stock<0)return toast("راجع اسم المنتج والسعر والكمية");try{if(id)await db.collection(C().products).doc(id).update(data);else await db.collection(C().products).add(data);closeProductForm();toast(id?"تم تعديل المنتج":"تمت إضافة المنتج")}catch(e){toast("حدث خطأ: "+e.message)}}
async function deleteProduct(id){if(latestOrders.some(o=>(o.items||[]).some(i=>i.productId===id)))return toast("لا يمكن حذف منتج مرتبط بطلبات سابقة");if(!confirm("هل أنت متأكد من حذف المنتج؟"))return;try{await db.collection(C().products).doc(id).delete();toast("تم حذف المنتج")}catch(e){toast(e.message)}}

/* Categories */
function renderCategoriesTable(){const grid=document.getElementById("categoryGrid");if(!grid)return;grid.innerHTML=categoriesCache.map(c=>{const ps=productsCache.filter(p=>p.category===c.id),qty=ps.reduce((s,p)=>s+Number(p.stock||0),0),value=ps.reduce((s,p)=>s+Number(p.stock||0)*Number(p.price||0),0);return`<article class="category-card"><div class="cat-top"><img src="${escapeHtml(c.image||"https://placehold.co/80x80/161418/c9a24b?text=LT")}" onerror="this.src='https://placehold.co/80x80/161418/c9a24b?text=LT'"><div><h3>${escapeHtml(c.name)}</h3><p>${num(ps.length)} منتج</p></div></div><div class="category-meta"><span>${num(qty)} قطعة</span><strong>${money(value)}</strong></div><div class="row-actions" style="margin-top:11px"><button class="mini" onclick="openCategoryForm('${c.id}')">✎</button><button class="mini" onclick="deleteCategory('${c.id}')">×</button></div></article>`}).join("")||`<div class="empty-note">لا توجد أقسام بعد.</div>`}
function openCategoryForm(id){const c=id?categoriesCache.find(x=>x.id===id):null;document.getElementById("categoryFormTitle").textContent=id?"تعديل قسم":"إضافة قسم";document.getElementById("cf_id").value=id||"";document.getElementById("cf_name").value=c?.name||"";document.getElementById("cf_order").value=c?.order??categoriesCache.length;resetImageBox("cf_image","cf_imagePreview","cf_uploadHint","cf_imageUrlManual",c?.image||"");document.getElementById("categoryFormOverlay").classList.add("open")}
function closeCategoryForm(){document.getElementById("categoryFormOverlay").classList.remove("open")}
async function saveCategory(){const id=document.getElementById("cf_id").value,data={name:document.getElementById("cf_name").value.trim(),image:document.getElementById("cf_image").value.trim(),order:Number(document.getElementById("cf_order").value)||0};if(!data.name)return toast("اكتب اسم القسم");try{if(id)await db.collection(C().categories).doc(id).update(data);else await db.collection(C().categories).add(data);closeCategoryForm();toast("تم حفظ القسم")}catch(e){toast(e.message)}}
async function deleteCategory(id){if(productsCache.some(p=>p.category===id))return toast("لا يمكن حذف قسم به منتجات");if(!confirm("حذف القسم؟"))return;try{await db.collection(C().categories).doc(id).delete();toast("تم حذف القسم")}catch(e){toast(e.message)}}

/* Orders + automatic inventory */
function renderOrdersTable(){const body=document.getElementById("ordersTableBody"),filter=document.getElementById("orderStatusFilter")?.value||"",list=latestOrders.filter(o=>!filter||o.status===filter);body.innerHTML=list.map(o=>`<tr><td><strong>${escapeHtml(o.id)}</strong></td><td><strong>${escapeHtml(o.customer?.name||"—")}</strong><small class="muted">${escapeHtml(o.customer?.phone||"")}</small></td><td>${(o.items||[]).map(i=>`${escapeHtml(i.name||getProduct(i.productId)?.name||"—")} × ${num(i.qty)}`).join("<br>")}</td><td class="money">${money(orderTotal(o))}</td><td><select class="status-select" onchange="updateOrderStatus('${o.id}',this.value)">${ORDER_STATUSES.map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></td><td>${formatDate(o.createdAt)}</td><td><button class="mini" onclick="viewOrder('${o.id}')">⌕</button></td></tr>`).join("")||`<tr><td colspan="7" class="empty-note">لا توجد طلبات.</td></tr>`}
document.getElementById("orderStatusFilter").addEventListener("change",renderOrdersTable);
async function updateOrderStatus(id,status){
  const ref=db.collection(C().orders).doc(id);
  try{
    const current=latestOrders.find(x=>x.id===id);
    if(!current) throw new Error("الطلب غير موجود");
    const paymentStatus=current.payment?.status||current.paymentStatus||"not_required";
    if(!["not_required","approved","paid"].includes(paymentStatus) && status!=="ملغي"){
      throw new Error("لا يمكن متابعة الطلب قبل تأكيد الدفع الإلكتروني.");
    }
    await db.runTransaction(async tx=>{
      const snap=await tx.get(ref); if(!snap.exists) throw new Error("الطلب غير موجود");
      const o={id:snap.id,...snap.data()},old=o.status; if(old===status)return;
      const grouped={};
      for(const item of (o.items||[])){const pid=item.productId;if(!pid)continue;grouped[pid]=(grouped[pid]||0)+Math.max(0,Number(item.qty||0));}
      const ids=Object.keys(grouped), productSnaps={};
      for(const pid of ids){const pref=db.collection(C().products).doc(pid);productSnaps[pid]=await tx.get(pref);if(!productSnaps[pid].exists)throw new Error("المنتج غير موجود: "+pid);}
      if(old!=="تم التسليم"&&status==="تم التسليم"){
        for(const pid of ids){const ps=productSnaps[pid],stock=Number(ps.data().stock||0),qty=grouped[pid];if(stock<qty)throw new Error(`المخزون غير كافٍ لـ ${ps.data().name||pid}`);}
        for(const pid of ids){const ps=productSnaps[pid],pref=db.collection(C().products).doc(pid),stock=Number(ps.data().stock||0),qty=grouped[pid];tx.update(pref,{stock:stock-qty,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});const mref=db.collection(C().inventoryMovements||"inventory_movements").doc();tx.set(mref,{productId:pid,productName:ps.data().name||"",type:"sale",quantity:qty,delta:-qty,before:stock,after:stock-qty,orderId:id,createdAt:firebase.firestore.FieldValue.serverTimestamp(),adminUid:currentUser?.uid||null});}
        tx.update(ref,{status,stockAdjusted:true,stockAdjustedAt:firebase.firestore.FieldValue.serverTimestamp()});
      } else if(old==="تم التسليم"&&status!=="تم التسليم"&&o.stockAdjusted!==false){
        for(const pid of ids){const ps=productSnaps[pid],pref=db.collection(C().products).doc(pid),stock=Number(ps.data().stock||0),qty=grouped[pid];tx.update(pref,{stock:stock+qty,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});const mref=db.collection(C().inventoryMovements||"inventory_movements").doc();tx.set(mref,{productId:pid,productName:ps.data().name||"",type:"sale_restore",quantity:qty,delta:qty,before:stock,after:stock+qty,orderId:id,createdAt:firebase.firestore.FieldValue.serverTimestamp(),adminUid:currentUser?.uid||null});}
        tx.update(ref,{status,stockAdjusted:false,stockRestoredAt:firebase.firestore.FieldValue.serverTimestamp()});
      } else tx.update(ref,{status});
    });
    await syncTrackingForOrder(id,status);
    toast("تم تحديث حالة الطلب والمخزون وتسجيل الحركة");
  }catch(e){toast(e.message||"تعذر تحديث الطلب");renderOrdersTable();}
}
async function syncTrackingForOrder(id,status,paymentPatch){
  const o=latestOrders.find(x=>x.id===id); if(!o)return;
  const items=(o.items||[]).map(i=>({productId:i.productId||"",name:i.name||getProduct(i.productId)?.name||"منتج",price:Number(i.price||getProduct(i.productId)?.price||0),qty:Number(i.qty||0)}));
  const patch={orderId:id,status,total:orderTotal(o),items,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),payment:o.payment||{}};
  if(paymentPatch) patch.payment={...(o.payment||{}),...paymentPatch};
  await db.collection(C().orderTracking||"order_tracking").doc(id).set(patch,{merge:true});
  if(o.customer?.phone){const phoneHash=await sha256Text(normalizePhoneForTracking(o.customer.phone));await db.collection("order_tracking_by_phone").doc(phoneHash).collection("orders").doc(id).set(patch,{merge:true});}
}
function viewOrder(id){const o=latestOrders.find(x=>x.id===id);if(!o)return;document.getElementById("orderModal").innerHTML=`<button class="modal-close" onclick="closeOrderModal()">×</button><div class="modal-head"><span>ORDER</span><h2>تفاصيل الطلب</h2><p>${escapeHtml(o.id)} · ${formatDate(o.createdAt)}</p></div><div class="compact-list">${(o.items||[]).map(i=>`<div class="compact-item"><div><strong>${escapeHtml(i.name||getProduct(i.productId)?.name||"—")}</strong><small>${num(i.qty)} × ${money(i.price||getProduct(i.productId)?.price||0)}</small></div><b class="money">${money((i.price||getProduct(i.productId)?.price||0)*Number(i.qty||0))}</b></div>`).join("")}</div><div style="padding:16px 0;border-top:1px solid #29262d;display:flex;justify-content:space-between"><span>الإجمالي</span><strong class="money">${money(orderTotal(o))}</strong></div><div class="report-row"><span>العميل</span><strong>${escapeHtml(o.customer?.name||"—")}</strong></div><div class="report-row"><span>الهاتف</span><strong>${escapeHtml(o.customer?.phone||"—")}</strong></div>`;document.getElementById("orderOverlay").classList.add("open")}
function closeOrderModal(){document.getElementById("orderOverlay").classList.remove("open")}


/* Coupons */
function couponUsedCount(c){return latestOrders.filter(o=>String(o.coupon?.code||"").toUpperCase()===String(c.code||"").toUpperCase()).length}
function renderCoupons(){const body=document.getElementById("couponsTableBody");if(!body)return;const now=new Date();body.innerHTML=couponsCache.slice().sort((a,b)=>String(a.code||"").localeCompare(String(b.code||""))).map(c=>{const used=couponUsedCount(c),limit=Number(c.usageLimit)||0,expired=c.expiresAt&&new Date(c.expiresAt)<now;const active=c.active!==false&&!expired&&(limit===0||used<limit);const type=c.type==="fixed"?"مبلغ ثابت":"نسبة";const exp=c.expiresAt?new Date(c.expiresAt).toLocaleString("ar-EG",{dateStyle:"short",timeStyle:"short"}):"بدون انتهاء";return `<tr><td><strong>${escapeHtml(String(c.code||"").toUpperCase())}</strong></td><td>${type}</td><td class="money">${num(c.value)}${c.type==="fixed"?" ج.م":"%"}</td><td class="money">${money(c.minOrder||0)}</td><td>${escapeHtml(exp)}</td><td>${num(used)} / ${limit?num(limit):"∞"}</td><td><span class="status ${active?"ok":"danger"}">${active?"مفعل":"متوقف"}</span></td><td><div class="row-actions"><button class="mini" onclick="openCouponForm('${c.id}')">✎</button><button class="mini" onclick="toggleCoupon('${c.id}')">${active?"⏸":"▶"}</button><button class="mini" onclick="deleteCoupon('${c.id}')">×</button></div></td></tr>`}).join("")||`<tr><td colspan="8" class="empty-note">لا توجد كوبونات حتى الآن.</td></tr>`}
function openCouponForm(id){const c=id?couponsCache.find(x=>x.id===id):null;document.getElementById("coupon_id").value=id||"";document.getElementById("couponFormTitle").textContent=id?"تعديل كوبون خصم":"إضافة كوبون خصم";document.getElementById("coupon_code").value=c?.code||"";document.getElementById("coupon_type").value=c?.type||"percent";document.getElementById("coupon_value").value=c?.value??"";document.getElementById("coupon_minOrder").value=c?.minOrder??0;document.getElementById("coupon_maxDiscount").value=c?.maxDiscount??0;document.getElementById("coupon_usageLimit").value=c?.usageLimit??0;document.getElementById("coupon_active").value=c?.active===false?"false":"true";document.getElementById("coupon_expiresAt").value=c?.expiresAt?String(c.expiresAt).slice(0,16):"";document.getElementById("couponFormOverlay").classList.add("open")}
function closeCouponForm(){document.getElementById("couponFormOverlay")?.classList.remove("open")}
async function saveCoupon(){
  const id=document.getElementById("coupon_id").value.trim();
  const code=document.getElementById("coupon_code").value.trim().toUpperCase().replace(/\s+/g,"");
  const type=document.getElementById("coupon_type").value;
  const value=Number(document.getElementById("coupon_value").value);
  const minOrder=Math.max(0,Number(document.getElementById("coupon_minOrder").value)||0);
  const maxDiscount=Math.max(0,Number(document.getElementById("coupon_maxDiscount").value)||0);
  const usageLimit=Math.max(0,Number(document.getElementById("coupon_usageLimit").value)||0);
  const expiresAt=document.getElementById("coupon_expiresAt").value||"";
  const active=document.getElementById("coupon_active").value==="true";
  if(!currentUser)return toast("سجّل دخول الأدمن أولاً");
  if(!code||!Number.isFinite(value)||value<=0)return toast("اكتب الكود وقيمة الخصم بشكل صحيح");
  if(type==="percent"&&value>100)return toast("النسبة لا يمكن أن تتجاوز 100%");
  const btn=document.querySelector('#couponFormOverlay .btn-primary');
  if(btn){btn.disabled=true;btn.textContent="جاري الحفظ...";}
  const data={code,type,value,minOrder,maxDiscount,usageLimit,expiresAt,active,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};
  try{
    if(id){
      await db.collection("coupons").doc(id).set(data,{merge:true});
    }else{
      await db.collection("coupons").doc(code).set({...data,usedCount:0,createdAt:firebase.firestore.FieldValue.serverTimestamp()});
    }
    closeCouponForm();
    toast("✓ تم حفظ الكوبون بنجاح");
  }catch(e){
    console.error("saveCoupon error",e);
    if(e?.code==="permission-denied") toast("Firebase رفض الحفظ: أضف قاعدة coupons للأدمن في Firestore Rules");
    else toast("تعذر حفظ الكوبون: "+(e?.message||"خطأ غير معروف"));
  }finally{
    if(btn){btn.disabled=false;btn.textContent="حفظ الكوبون";}
  }
}
async function toggleCoupon(id){const c=couponsCache.find(x=>x.id===id);if(!c)return;try{await db.collection("coupons").doc(id).update({active:c.active===false,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});toast(c.active===false?"تم تفعيل الكوبون":"تم إيقاف الكوبون")}catch(e){toast(e.message)}}
async function deleteCoupon(id){if(!confirm("حذف كوبون الخصم؟"))return;try{await db.collection("coupons").doc(id).delete();toast("تم حذف الكوبون")}catch(e){toast(e.message)}}

/* Customer messages */
function formatMsgDate(v){try{if(v?.toDate)return v.toDate().toLocaleString("ar-EG");return v?new Date(v).toLocaleString("ar-EG"):"—"}catch{return "—"}}
function renderMessages(){const body=document.getElementById("messagesTableBody");if(!body)return;body.innerHTML=messagesCache.map(m=>`<tr><td>${escapeHtml(formatMsgDate(m.createdAt))}</td><td><strong>${escapeHtml(m.name||"—")}</strong></td><td>${escapeHtml(m.phone||"—")}</td><td style="min-width:260px;white-space:pre-wrap">${escapeHtml(m.message||"")}</td><td><span class="status ${m.status==="read"?"ok":"warn"}">${m.status==="read"?"مقروء":"جديد"}</span></td><td><div class="row-actions">${m.status!=="read"?`<button class="mini" onclick="markMessageRead('${m.id}')">✓</button>`:""}<button class="mini" onclick="deleteMessage('${m.id}')">×</button></div></td></tr>`).join("")||`<tr><td colspan="6" class="empty-note">لا توجد رسائل حتى الآن.</td></tr>`}
async function markMessageRead(id){try{await db.collection("messages").doc(id).set({status:"read",readAt:firebase.firestore.FieldValue.serverTimestamp(),readBy:currentUser?.uid||null},{merge:true});toast("تم تعليم الرسالة كمقروءة")}catch(e){toast("تعذر تحديث الرسالة: "+e.message)}}
async function deleteMessage(id){if(!confirm("حذف الرسالة؟"))return;try{await db.collection("messages").doc(id).delete();toast("تم حذف الرسالة")}catch(e){toast("تعذر حذف الرسالة: "+e.message)}}
function fillMessagingSettings(){const en=document.getElementById("messagingEnabled"),wa=document.getElementById("messagingWhatsapp");if(en)en.checked=socialLinks.messagingEnabled!==false && !!(socialLinks.messagingWhatsapp||socialLinks.whatsapp);if(wa)wa.value=socialLinks.messagingWhatsapp||socialLinks.whatsapp||""}
async function saveMessagingSettings(){const data={messagingEnabled:!!document.getElementById("messagingEnabled")?.checked,messagingWhatsapp:document.getElementById("messagingWhatsapp")?.value.trim()||"",updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{await db.collection("socialLinks").doc("main").set(data,{merge:true});socialLinks={...socialLinks,...data};fillMessagingSettings();toast("تم حفظ إعدادات الرسائل")}catch(e){toast("تعذر حفظ إعدادات الرسائل: "+e.message)}}

/* Payments, branches and social links */
async function loadSettingsOnce(){
  try{const [p,b]=await Promise.all([db.collection("storeSettings").doc("main").get(),db.collection("socialLinks").doc("main").get()]);if(p.exists)storeSettings={...storeSettings,...p.data()};if(b.exists)socialLinks=b.data();fillSettingsForms();fillSocialLinks();}catch(e){console.error(e)}
}
function fillSettingsForms(){
  const ids=["payCashEnabled","payInstapayEnabled","payWalletEnabled"];["cashOnDeliveryEnabled","instapayEnabled","walletEnabled"].forEach((k,i)=>{const el=document.getElementById(ids[i]);if(el)el.checked=!!storeSettings[k]});
  const map={instaName:storeSettings.instapay?.name||"",instaNumber:storeSettings.instapay?.number||"",instaInstructions:storeSettings.instapay?.instructions||"",walletName:storeSettings.wallet?.name||"",walletNumber:storeSettings.wallet?.number||"",walletNetwork:storeSettings.wallet?.network||"",walletInstructions:storeSettings.wallet?.instructions||""};Object.entries(map).forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.value=v});
}
async function savePaymentSettings(){
  const data={cashOnDeliveryEnabled:!!document.getElementById("payCashEnabled")?.checked,instapayEnabled:!!document.getElementById("payInstapayEnabled")?.checked,walletEnabled:!!document.getElementById("payWalletEnabled")?.checked,instapay:{name:document.getElementById("instaName")?.value.trim()||"",number:document.getElementById("instaNumber")?.value.trim()||"",instructions:document.getElementById("instaInstructions")?.value.trim()||""},wallet:{name:document.getElementById("walletName")?.value.trim()||"",number:document.getElementById("walletNumber")?.value.trim()||"",network:document.getElementById("walletNetwork")?.value.trim()||"",instructions:document.getElementById("walletInstructions")?.value.trim()||""},updatedAt:firebase.firestore.FieldValue.serverTimestamp()};
  try{await db.collection("storeSettings").doc("main").set(data,{merge:true});storeSettings={...storeSettings,...data};toast("تم حفظ إعدادات الدفع");}catch(e){toast("تعذر حفظ إعدادات الدفع: "+e.message)}
}
function renderPaymentRequests(){const body=document.getElementById("paymentRequestsBody");if(!body)return;body.innerHTML=paymentRequestsCache.map(r=>{const st=r.status||"pending";const badge=st==="approved"?"ok":st==="rejected"?"danger":"warn";return `<tr><td><strong>${escapeHtml(r.orderId||"—")}</strong></td><td>${escapeHtml(r.methodName||r.method||"—")}</td><td class="money">${money(r.amount)}</td><td>${escapeHtml(r.senderPhone||"—")}</td><td>${r.proofUrl?`<button class="mini" onclick="openProof('${escapeHtml(r.proofUrl)}')">عرض</button>`:"—"}</td><td><span class="status ${badge}">${st==="approved"?"تم التأكيد":st==="rejected"?"مرفوض":"بانتظار المراجعة"}</span></td><td>${st==="pending"?`<div class="row-actions"><button class="mini ok-btn" onclick="reviewPayment('${r.id}','approved')">✓</button><button class="mini danger-btn" onclick="reviewPayment('${r.id}','rejected')">×</button></div>`:"—"}</td></tr>`}).join("")||`<tr><td colspan="7" class="empty-note">لا توجد طلبات دفع حاليًا.</td></tr>`}
async function reviewPayment(id,status){const r=paymentRequestsCache.find(x=>x.id===id);if(!r)return;let reason="";if(status==="rejected"){reason=prompt("سبب رفض الدفع (اختياري):","")??"";}try{await db.collection("paymentRequests").doc(id).update({status,rejectionReason:reason,reviewedBy:currentUser?.uid||null,reviewedAt:firebase.firestore.FieldValue.serverTimestamp()});if(r.orderId){await db.collection(C().orders).doc(r.orderId).set({payment:{method:r.method,status,senderPhone:r.senderPhone||"",proofUrl:r.proofUrl||"",rejectionReason:reason,reviewedAt:firebase.firestore.FieldValue.serverTimestamp()}},{merge:true});await syncTrackingForOrder(r.orderId,(latestOrders.find(o=>o.id===r.orderId)?.status)||"جديد",{method:r.method,status,rejectionReason:reason});}toast(status==="approved"?"تم تأكيد الدفع": "تم رفض الدفع");}catch(e){toast("تعذر تحديث الدفع: "+e.message)}}
function openProof(url){document.getElementById("proofImage").src=url;document.getElementById("proofOverlay").classList.add("open")}
function closeProof(){document.getElementById("proofOverlay").classList.remove("open")}
function renderBranches(){const body=document.getElementById("branchesBody");if(!body)return;body.innerHTML=branchesCache.map(b=>`<tr><td><strong>${escapeHtml(b.name||"—")}</strong></td><td>${escapeHtml(b.address||"—")}</td><td>${escapeHtml(b.phone||"—")}</td><td>${escapeHtml(b.whatsapp||"—")}</td><td>${b.maps?`<a class="mini-link" href="${escapeHtml(b.maps)}" target="_blank" rel="noopener">فتح الخريطة</a>`:"—"}</td><td><div class="row-actions"><button class="mini" onclick="openBranchForm('${b.id}')">✎</button><button class="mini" onclick="deleteBranch('${b.id}')">×</button></div></td></tr>`).join("")||`<tr><td colspan="6" class="empty-note">لم تضف فروعًا بعد.</td></tr>`}
function openBranchForm(id){const b=id?branchesCache.find(x=>x.id===id):null;document.getElementById("bf_id").value=id||"";document.getElementById("bf_name").value=b?.name||"";document.getElementById("bf_address").value=b?.address||"";document.getElementById("bf_phone").value=b?.phone||"";document.getElementById("bf_whatsapp").value=b?.whatsapp||"";document.getElementById("bf_maps").value=b?.maps||"";document.getElementById("bf_hours").value=b?.hours||"";document.getElementById("branchFormOverlay").classList.add("open")}
function closeBranchForm(){document.getElementById("branchFormOverlay").classList.remove("open")}
async function saveBranch(){const id=document.getElementById("bf_id").value,data={name:document.getElementById("bf_name").value.trim(),address:document.getElementById("bf_address").value.trim(),phone:document.getElementById("bf_phone").value.trim(),whatsapp:document.getElementById("bf_whatsapp").value.trim(),maps:document.getElementById("bf_maps").value.trim(),hours:document.getElementById("bf_hours").value.trim(),order:branchesCache.findIndex(x=>x.id===id)>=0?branchesCache.findIndex(x=>x.id===id):branchesCache.length,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!data.name||!data.address)return toast("اكتب اسم الفرع والعنوان");try{if(id)await db.collection("branches").doc(id).update(data);else await db.collection("branches").add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()});closeBranchForm();toast("تم حفظ الفرع")}catch(e){toast(e.message)}}
async function deleteBranch(id){if(!confirm("حذف هذا الفرع؟"))return;try{await db.collection("branches").doc(id).delete();toast("تم حذف الفرع")}catch(e){toast(e.message)}}
function fillSocialLinks(){const map={socialWhatsapp:socialLinks.whatsapp||"",socialFacebook:socialLinks.facebook||"",socialTiktok:socialLinks.tiktok||"",socialInstagram:socialLinks.instagram||"",socialYoutube:socialLinks.youtube||"",socialTelegram:socialLinks.telegram||"",messagingWhatsapp:socialLinks.messagingWhatsapp||socialLinks.whatsapp||""};Object.entries(map).forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.value=v})}
async function saveSocialLinks(){const data={whatsapp:document.getElementById("socialWhatsapp")?.value.trim()||"",facebook:document.getElementById("socialFacebook")?.value.trim()||"",tiktok:document.getElementById("socialTiktok")?.value.trim()||"",instagram:document.getElementById("socialInstagram")?.value.trim()||"",youtube:document.getElementById("socialYoutube")?.value.trim()||"",telegram:document.getElementById("socialTelegram")?.value.trim()||"",updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{await db.collection("socialLinks").doc("main").set(data,{merge:true});socialLinks={...socialLinks,...data};toast("تم حفظ الروابط")}catch(e){toast("تعذر حفظ الروابط: "+e.message)}}

document.getElementById("couponFormOverlay")?.addEventListener("click",e=>{if(e.target.id==="couponFormOverlay")closeCouponForm()});document.getElementById("branchFormOverlay")?.addEventListener("click",e=>{if(e.target.id==="branchFormOverlay")closeBranchForm()});document.getElementById("proofOverlay")?.addEventListener("click",e=>{if(e.target.id==="proofOverlay")closeProof()});
loadSettingsOnce();

/* Sales / reports */
function renderSales(){const total=completedRevenue(),qty=latestOrders.filter(isCompleted).reduce((s,o)=>s+(o.items||[]).reduce((a,i)=>a+Number(i.qty||0),0),0),top=productsCache.slice().sort((a,b)=>salesForProduct(b.id)-salesForProduct(a.id))[0];document.getElementById("salesSummary").innerHTML=`<div class="sales-box"><small>إجمالي المبيعات</small><strong>${money(total)}</strong></div><div class="sales-box"><small>إجمالي القطع المباعة</small><strong>${num(qty)}</strong></div><div class="sales-box"><small>أعلى صنف مبيعًا</small><strong>${escapeHtml(top?.name||"—")}</strong></div>`;document.getElementById("salesTableBody").innerHTML=productsCache.slice().sort((a,b)=>salesForProduct(b.id)-salesForProduct(a.id)).map(p=>`<tr><td><strong>${escapeHtml(p.name)}</strong></td><td class="money">${money(p.price)}</td><td>${num(soldForProduct(p.id))}</td><td class="money">${money(salesForProduct(p.id))}</td><td>${num(p.stock)}</td></tr>`).join("")||`<tr><td colspan="5" class="empty-note">لا توجد مبيعات.</td></tr>`}
function renderReports(){const low=lowProducts(),out=productsCache.filter(p=>Number(p.stock||0)===0),completed=latestOrders.filter(isCompleted),avg=completed.length?completed.reduce((s,o)=>s+orderTotal(o),0)/completed.length:0,best=productsCache.slice().sort((a,b)=>salesForProduct(b.id)-salesForProduct(a.id))[0];document.getElementById("reportGrid").innerHTML=`<article class="report-box"><h3>المخزون</h3><div class="report-row"><span>عدد المنتجات</span><strong>${num(productsCache.length)}</strong></div><div class="report-row"><span>القطع المتاحة</span><strong>${num(productsCache.reduce((s,p)=>s+Number(p.stock||0),0))}</strong></div><div class="report-row"><span>قيمة المخزون</span><strong>${money(stockValue())}</strong></div></article><article class="report-box"><h3>المبيعات</h3><div class="report-row"><span>إجمالي المبيعات</span><strong>${money(completedRevenue())}</strong></div><div class="report-row"><span>متوسط الطلب المكتمل</span><strong>${money(avg)}</strong></div><div class="report-row"><span>الأكثر مبيعًا</span><strong>${escapeHtml(best?.name||"—")}</strong></div></article><article class="report-box"><h3>الطلبات</h3><div class="report-row"><span>إجمالي الطلبات</span><strong>${num(latestOrders.length)}</strong></div><div class="report-row"><span>قيد التنفيذ</span><strong>${num(latestOrders.filter(o=>["جديد","قيد التجهيز","تم الشحن"].includes(o.status)).length)}</strong></div><div class="report-row"><span>طلبات مكتملة</span><strong>${num(completed.length)}</strong></div></article><article class="report-box"><h3>تنبيهات</h3><div class="report-row"><span>مخزون منخفض</span><strong>${num(low.length)}</strong></div><div class="report-row"><span>منتجات نافدة</span><strong>${num(out.length)}</strong></div><div class="report-row"><span>الحد الأدنى</span><strong>حسب كل منتج</strong></div></article>`}

/* Images */
async function handleImageUpload(fileInputEl,hiddenInputId,previewId,hintId,barId,folder){const file=fileInputEl.files[0];if(!file)return;if(!file.type.startsWith("image/"))return toast("اختر ملف صورة");if(file.size>5*1024*1024)return toast("الصورة يجب ألا تتجاوز 5 ميجا");const wrap=document.getElementById(barId+"Wrap"),bar=document.getElementById(barId),hint=document.getElementById(hintId);wrap.style.display="block";bar.style.width="40%";hint.textContent="جاري الرفع...";try{const formData=new FormData();formData.append("file",file);formData.append("upload_preset",CLOUDINARY_UPLOAD_PRESET);formData.append("folder",folder);const response=await fetch(CLOUDINARY_UPLOAD_URL,{method:"POST",body:formData});const data=await response.json();if(!response.ok){console.error("Cloudinary upload error:",data);hint.textContent="فشل الرفع: "+(data?.error?.message||"خطأ غير معروف");wrap.style.display="none";return}bar.style.width="100%";const url=data.secure_url;document.getElementById(hiddenInputId).value=url;const img=document.getElementById(previewId);img.src=url;img.style.display="block";hint.style.display="none";wrap.style.display="none";const btn=document.getElementById(hiddenInputId+"RemoveBtn");if(btn)btn.classList.add("show")}catch(e){console.error("Upload failed:",e);hint.textContent="فشل الرفع: "+(e.message||e);wrap.style.display="none"}}
function setManualUrl(urlInputId,hiddenInputId,previewId,hintId){const url=document.getElementById(urlInputId).value.trim();if(!url)return;document.getElementById(hiddenInputId).value=url;const img=document.getElementById(previewId);img.src=url;img.style.display="block";document.getElementById(hintId).style.display="none";const btn=document.getElementById(hiddenInputId+"RemoveBtn");if(btn)btn.classList.add("show")}
function resetImageBox(hiddenInputId,previewId,hintId,urlManualId,url){document.getElementById(hiddenInputId).value=url||"";const img=document.getElementById(previewId),hint=document.getElementById(hintId),btn=document.getElementById(hiddenInputId+"RemoveBtn");document.getElementById(urlManualId).value="";if(url){img.src=url;img.style.display="block";hint.style.display="none";if(btn)btn.classList.add("show")}else{img.removeAttribute("src");img.style.display="none";hint.style.display="block";hint.textContent="اضغط لاختيار صورة من جهازك";if(btn)btn.classList.remove("show")}}
function removeImage(hiddenInputId,previewId,hintId,removeBtnId){if(!confirm("هل تريد حذف الصورة؟"))return;document.getElementById(hiddenInputId).value="";const img=document.getElementById(previewId),hint=document.getElementById(hintId),btn=document.getElementById(removeBtnId),fileInput=document.getElementById(hiddenInputId.replace(/_image$/,"_imageFile")),urlManual=document.getElementById(hiddenInputId.replace(/_image$/,"_imageUrlManual"));img.removeAttribute("src");img.style.display="none";hint.style.display="block";hint.textContent="اضغط لاختيار صورة من جهازك";if(btn)btn.classList.remove("show");if(fileInput)fileInput.value="";if(urlManual)urlManual.value=""}

/* Overlay close */
["productFormOverlay","categoryFormOverlay","orderOverlay"].forEach(id=>document.getElementById(id).addEventListener("click",e=>{if(e.target.id===id)e.currentTarget.classList.remove("open")}));

function normalizePhoneForTracking(phone){let p=String(phone||"").replace(/[^0-9+]/g,"");if(p.startsWith("+20"))p="0"+p.slice(3);else if(p.startsWith("20")&&p.length>=12)p="0"+p.slice(2);return p}
async function sha256Text(value){const data=new TextEncoder().encode(String(value));const hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("")}
